/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.codewithsrb.BookManagement.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
/** Book detail value */
@org.apache.avro.specific.AvroGenerated
public class BookValue extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -772882313307242880L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BookValue\",\"namespace\":\"com.codewithsrb.BookManagement.schema\",\"doc\":\"Book detail value\",\"fields\":[{\"name\":\"title\",\"type\":\"string\",\"default\":\"None\"},{\"name\":\"author\",\"type\":\"string\",\"default\":\"None\"},{\"name\":\"bookLanguage\",\"type\":\"string\",\"default\":\"None\"},{\"name\":\"price\",\"type\":\"double\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BookValue> ENCODER =
      new BinaryMessageEncoder<BookValue>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BookValue> DECODER =
      new BinaryMessageDecoder<BookValue>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<BookValue> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<BookValue> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<BookValue>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this BookValue to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a BookValue from a ByteBuffer. */
  public static BookValue fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence title;
  @Deprecated public java.lang.CharSequence author;
  @Deprecated public java.lang.CharSequence bookLanguage;
  @Deprecated public double price;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BookValue() {}

  /**
   * All-args constructor.
   * @param title The new value for title
   * @param author The new value for author
   * @param bookLanguage The new value for bookLanguage
   * @param price The new value for price
   */
  public BookValue(java.lang.CharSequence title, java.lang.CharSequence author, java.lang.CharSequence bookLanguage, java.lang.Double price) {
    this.title = title;
    this.author = author;
    this.bookLanguage = bookLanguage;
    this.price = price;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return title;
    case 1: return author;
    case 2: return bookLanguage;
    case 3: return price;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: title = (java.lang.CharSequence)value$; break;
    case 1: author = (java.lang.CharSequence)value$; break;
    case 2: bookLanguage = (java.lang.CharSequence)value$; break;
    case 3: price = (java.lang.Double)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'title' field.
   * @return The value of the 'title' field.
   */
  public java.lang.CharSequence getTitle() {
    return title;
  }

  /**
   * Sets the value of the 'title' field.
   * @param value the value to set.
   */
  public void setTitle(java.lang.CharSequence value) {
    this.title = value;
  }

  /**
   * Gets the value of the 'author' field.
   * @return The value of the 'author' field.
   */
  public java.lang.CharSequence getAuthor() {
    return author;
  }

  /**
   * Sets the value of the 'author' field.
   * @param value the value to set.
   */
  public void setAuthor(java.lang.CharSequence value) {
    this.author = value;
  }

  /**
   * Gets the value of the 'bookLanguage' field.
   * @return The value of the 'bookLanguage' field.
   */
  public java.lang.CharSequence getBookLanguage() {
    return bookLanguage;
  }

  /**
   * Sets the value of the 'bookLanguage' field.
   * @param value the value to set.
   */
  public void setBookLanguage(java.lang.CharSequence value) {
    this.bookLanguage = value;
  }

  /**
   * Gets the value of the 'price' field.
   * @return The value of the 'price' field.
   */
  public java.lang.Double getPrice() {
    return price;
  }

  /**
   * Sets the value of the 'price' field.
   * @param value the value to set.
   */
  public void setPrice(java.lang.Double value) {
    this.price = value;
  }

  /**
   * Creates a new BookValue RecordBuilder.
   * @return A new BookValue RecordBuilder
   */
  public static com.codewithsrb.BookManagement.schema.BookValue.Builder newBuilder() {
    return new com.codewithsrb.BookManagement.schema.BookValue.Builder();
  }

  /**
   * Creates a new BookValue RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BookValue RecordBuilder
   */
  public static com.codewithsrb.BookManagement.schema.BookValue.Builder newBuilder(com.codewithsrb.BookManagement.schema.BookValue.Builder other) {
    return new com.codewithsrb.BookManagement.schema.BookValue.Builder(other);
  }

  /**
   * Creates a new BookValue RecordBuilder by copying an existing BookValue instance.
   * @param other The existing instance to copy.
   * @return A new BookValue RecordBuilder
   */
  public static com.codewithsrb.BookManagement.schema.BookValue.Builder newBuilder(com.codewithsrb.BookManagement.schema.BookValue other) {
    return new com.codewithsrb.BookManagement.schema.BookValue.Builder(other);
  }

  /**
   * RecordBuilder for BookValue instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BookValue>
    implements org.apache.avro.data.RecordBuilder<BookValue> {

    private java.lang.CharSequence title;
    private java.lang.CharSequence author;
    private java.lang.CharSequence bookLanguage;
    private double price;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.codewithsrb.BookManagement.schema.BookValue.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.title)) {
        this.title = data().deepCopy(fields()[0].schema(), other.title);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.author)) {
        this.author = data().deepCopy(fields()[1].schema(), other.author);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.bookLanguage)) {
        this.bookLanguage = data().deepCopy(fields()[2].schema(), other.bookLanguage);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.price)) {
        this.price = data().deepCopy(fields()[3].schema(), other.price);
        fieldSetFlags()[3] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing BookValue instance
     * @param other The existing instance to copy.
     */
    private Builder(com.codewithsrb.BookManagement.schema.BookValue other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.title)) {
        this.title = data().deepCopy(fields()[0].schema(), other.title);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.author)) {
        this.author = data().deepCopy(fields()[1].schema(), other.author);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.bookLanguage)) {
        this.bookLanguage = data().deepCopy(fields()[2].schema(), other.bookLanguage);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.price)) {
        this.price = data().deepCopy(fields()[3].schema(), other.price);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'title' field.
      * @return The value.
      */
    public java.lang.CharSequence getTitle() {
      return title;
    }

    /**
      * Sets the value of the 'title' field.
      * @param value The value of 'title'.
      * @return This builder.
      */
    public com.codewithsrb.BookManagement.schema.BookValue.Builder setTitle(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.title = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'title' field has been set.
      * @return True if the 'title' field has been set, false otherwise.
      */
    public boolean hasTitle() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'title' field.
      * @return This builder.
      */
    public com.codewithsrb.BookManagement.schema.BookValue.Builder clearTitle() {
      title = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'author' field.
      * @return The value.
      */
    public java.lang.CharSequence getAuthor() {
      return author;
    }

    /**
      * Sets the value of the 'author' field.
      * @param value The value of 'author'.
      * @return This builder.
      */
    public com.codewithsrb.BookManagement.schema.BookValue.Builder setAuthor(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.author = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'author' field has been set.
      * @return True if the 'author' field has been set, false otherwise.
      */
    public boolean hasAuthor() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'author' field.
      * @return This builder.
      */
    public com.codewithsrb.BookManagement.schema.BookValue.Builder clearAuthor() {
      author = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'bookLanguage' field.
      * @return The value.
      */
    public java.lang.CharSequence getBookLanguage() {
      return bookLanguage;
    }

    /**
      * Sets the value of the 'bookLanguage' field.
      * @param value The value of 'bookLanguage'.
      * @return This builder.
      */
    public com.codewithsrb.BookManagement.schema.BookValue.Builder setBookLanguage(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.bookLanguage = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'bookLanguage' field has been set.
      * @return True if the 'bookLanguage' field has been set, false otherwise.
      */
    public boolean hasBookLanguage() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'bookLanguage' field.
      * @return This builder.
      */
    public com.codewithsrb.BookManagement.schema.BookValue.Builder clearBookLanguage() {
      bookLanguage = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'price' field.
      * @return The value.
      */
    public java.lang.Double getPrice() {
      return price;
    }

    /**
      * Sets the value of the 'price' field.
      * @param value The value of 'price'.
      * @return This builder.
      */
    public com.codewithsrb.BookManagement.schema.BookValue.Builder setPrice(double value) {
      validate(fields()[3], value);
      this.price = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'price' field has been set.
      * @return True if the 'price' field has been set, false otherwise.
      */
    public boolean hasPrice() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'price' field.
      * @return This builder.
      */
    public com.codewithsrb.BookManagement.schema.BookValue.Builder clearPrice() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BookValue build() {
      try {
        BookValue record = new BookValue();
        record.title = fieldSetFlags()[0] ? this.title : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.author = fieldSetFlags()[1] ? this.author : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.bookLanguage = fieldSetFlags()[2] ? this.bookLanguage : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.price = fieldSetFlags()[3] ? this.price : (java.lang.Double) defaultValue(fields()[3]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BookValue>
    WRITER$ = (org.apache.avro.io.DatumWriter<BookValue>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BookValue>
    READER$ = (org.apache.avro.io.DatumReader<BookValue>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
